[package]
name = "klypse-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ashpd.workspace = true
async-channel.workspace = true
async-trait.workspace = true
chrono.workspace = true
futures-lite.workspace = true
global-hotkey.workspace = true
image.workspace = true
gtk.workspace = true
klypse-domain = { path = "../klypse-domain" }
tempfile.workspace = true
url.workspace = true
uuid.workspace = true
x11rb.workspace = true

[dev-dependencies]
