[workspace]
resolver = "2"
members = [
  "crates/klypse-domain",
  "crates/klypse-platform",
  "crates/klypse-storage",
  "crates/klypse-media",
  "crates/klypse-image",
  "crates/klypse-app",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/Roadmvn/Klypse"

[workspace.dependencies]
anyhow = "1.0.103"
ashpd = { version = "0.13.12", default-features = false, features = ["async-io", "gtk4", "screenshot", "screencast", "global_shortcuts"] }
async-channel = "2.5.0"
async-trait = "0.1"
chrono = { version = "0.4.45", features = ["serde"] }
cairo-rs = "0.22.0"
clap = { version = "4", features = ["derive"] }
directories = "6.0.0"
gettext-rs = { version = "0.7.7", features = ["gettext-system"] }
futures-lite = "2.6.1"
global-hotkey = "0.8.0"
gstreamer = "0.25.3"
gstreamer-app = "0.25.2"
gstreamer-pbutils = "0.25.2"
gstreamer-video = "0.25.3"
gtk = { package = "gtk4", version = "0.11.4", features = ["v4_10"] }
image = "0.25.10"
libadwaita = { version = "0.9.2", features = ["v1_4"] }
pango = "0.22.8"
pangocairo = "0.22.0"
rusqlite = { version = "0.40.1", features = ["chrono"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
tempfile = "3.27.0"
thiserror = "2.0.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.23.5", features = ["v4", "serde"] }
x11rb = { version = "0.13.2", features = ["randr", "composite", "xfixes"] }
url = "2"
