[package]
name = "klypse-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
chrono.workspace = true
directories.workspace = true
gstreamer.workspace = true
gstreamer-pbutils.workspace = true
image.workspace = true
klypse-domain = { path = "../klypse-domain" }
klypse-media = { path = "../klypse-media" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
