[package]
name = "klypse-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "klypse"
path = "src/main.rs"

[dependencies]
async-channel.workspace = true
chrono.workspace = true
clap.workspace = true
gettext-rs.workspace = true
gtk.workspace = true
klypse-domain = { path = "../klypse-domain" }
klypse-media = { path = "../klypse-media" }
klypse-platform = { path = "../klypse-platform" }
klypse-storage = { path = "../klypse-storage" }
libadwaita.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
